@startuml

title __AUTH's Class Diagram__\n

  namespace dev.spiritworker {
    namespace server.auth {
      class dev.spiritworker.server.auth.AuthPacketHandler {
          {static} + handle()
          {static} - handleClientLogin()
          {static} - handleClientLoginGameForge()
          {static} - handleClientLogoutServerListReq()
          {static} - handleClientServerConnectRequest()
          {static} - handleClientServerListRequest()
      }
    }
  }
  

  namespace dev.spiritworker {
    namespace server.auth {
      class dev.spiritworker.server.auth.AuthServer {
          - gameServers : Map<Integer, ServerData>
          + AuthServer()
          + getGameServers()
          + getServerDataById()
          + onStart()
          + registerServer()
      }
    }
  }
  

  namespace dev.spiritworker {
    namespace server.auth {
      class dev.spiritworker.server.auth.AuthServerInitializer {
          - server : AuthServer
          + AuthServerInitializer()
          + initChannel()
      }
    }
  }
  

  namespace dev.spiritworker {
    namespace server.auth {
      class dev.spiritworker.server.auth.AuthSession {
          - mac : String
          - server : AuthServer
          - username : String
          + AuthSession()
          + getMac()
          + getServer()
          + getUsername()
          + onConnect()
          + onDisconnect()
          + setMac()
          + setUsername()
          # handleMessage()
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
