@startuml

title __SPIRITWORKER's Class Diagram__\n

  namespace dev.spiritworker {
    class dev.spiritworker.Config {
        + AuthServerIp : String
        + AuthServerPort : int
        {static} + DATA_FOLDER : String
        + DatabaseCollection : String
        + DatabaseUrl : String
        + GameServerId : int
        + GameServerIp : String
        + GameServerName : String
        + GameServerPort : int
        + LOG_PACKETS : boolean
        + PACKETS_FOLDER : String
        + RESOURCE_FOLDER : String
        + WorldServerIp : String
        + WorldServerPort : int
    }
  }
  

  namespace dev.spiritworker {
    class dev.spiritworker.Constants {
        {static} + INVENTORY_SLOTS_PER_UPGRADE : int
        {static} + LOADOUT_COLUMNS : int
        {static} + LOADOUT_COLUMN_SIZE : int
        {static} + MAX_EMOTE_SLOTS : int
        {static} + MAX_UPGRADES : int
    }
  }
  

  namespace dev.spiritworker {
    class dev.spiritworker.SpiritWorker {
        {static} + MODE : RunMode
        {static} - config : Config
        {static} - configFile : File
        {static} - gson : Gson
        {static} - log : Logger
        {static} + getConfig()
        {static} + getGsonFactory()
        {static} + getLogger()
        {static} + loadConfig()
        {static} + main()
        {static} + saveConfig()
    }
  }
  

  namespace dev.spiritworker {
    enum RunMode {
      AUTH
      BOTH
      GAME
    }
  }
  

  dev.spiritworker.SpiritWorker +-down- dev.spiritworker.SpiritWorker.RunMode


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
