@startuml

title __WORLD's Class Diagram__\n

  namespace dev.spiritworker {
    namespace server.world {
      class dev.spiritworker.server.world.WorldPacketHandler {
          {static} + handle()
          {static} - handleClientActivateSkill()
          {static} - handleClientAppearancePick()
          {static} - handleClientChannelInfo()
          {static} - handleClientCharacterUpdateSpecialOptionList()
          {static} - handleClientChatNormal()
          {static} - handleClientConnectWorldServer()
          {static} - handleClientCreateMaze()
          {static} - handleClientDoGesture()
          {static} - handleClientEnteredMaze()
          {static} - handleClientGestureSlotUpdate()
          {static} - handleClientInfoRequest()
          {static} - handleClientItemBreak()
          {static} - handleClientItemCombine()
          {static} - handleClientItemDivide()
          {static} - handleClientItemDye()
          {static} - handleClientItemInvenInfo()
          {static} - handleClientItemMove()
          {static} - handleClientItemUpdateSlotInfo()
          {static} - handleClientItemUpgrade()
          {static} - handleClientItemUse()
          {static} - handleClientKeepAlive()
          {static} - handleClientLeaveMaze()
          {static} - handleClientMazePortalEnter()
          {static} - handleClientMovementCancelGesture()
          {static} - handleClientMovementJump()
          {static} - handleClientMovementMove()
          {static} - handleClientMovementStop()
          {static} - handleClientQuitMaze()
          {static} - handleClientRequestLogout()
          {static} - handleClientRequestPlayers()
          {static} - handleClientResetPositionRequest()
          {static} - handleClientUpgradeSkill()
          {static} - handleClientUpgradeSkillModifier()
      }
    }
  }
  

  namespace dev.spiritworker {
    namespace server.world {
      class dev.spiritworker.server.world.WorldServer {
          - channelId : int
          - chatHandler : ChatManager
          - defaultDistrict : District
          - districts : Int2ObjectMap<District>
          - gameServer : GameServer
          - itemHandler : ItemManager
          - mazeManager : MazeManager
          - mazes : Set<Maze>
          - pool : ExecutorService
          - serverLoop : WorldServerLoop
          + WorldServer()
          + deregisterMaze()
          + getChannelId()
          + getChatManager()
          + getDefaultDistrict()
          + getDistrictById()
          + getGameServer()
          + getItemManager()
          + getMazeManager()
          + onStart()
          + onTick()
          + registerMaze()
          + setChannelId()
          - setupDistricts()
      }
    }
  }
  

  namespace dev.spiritworker {
    namespace server.world {
      class dev.spiritworker.server.world.WorldServerInitializer {
          - server : WorldServer
          + WorldServerInitializer()
          + initChannel()
      }
    }
  }
  

  namespace dev.spiritworker {
    namespace server.world {
      class dev.spiritworker.server.world.WorldServerLoop {
          {static} + TICK_RATE : int
          - running : boolean
          - server : WorldServer
          + WorldServerLoop()
          + getServer()
          + run()
      }
    }
  }
  

  namespace dev.spiritworker {
    namespace server.world {
      class dev.spiritworker.server.world.WorldSession {
          - character : GameCharacter
          - server : WorldServer
          + WorldSession()
          + getCharacter()
          + getGameServer()
          + getServer()
          + isAuthenticated()
          + onConnect()
          + onDisconnect()
          + setCharacter()
          # handleMessage()
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
