@startuml

title __GAME's Class Diagram__\n

  namespace dev.spiritworker {
    namespace server.game {
      class dev.spiritworker.server.game.GamePacketHandler {
          {static} + handle()
          {static} - handleClientCharacterListRequest()
          {static} - handleClientConnectGameServer()
          {static} - handleClientCreateCharacter()
          {static} - handleClientDeleteCharacter()
          {static} - handleClientLogoutServerReq()
          {static} - handleClientPlayGameRequest()
          {static} - handleClientRequestLogout()
          {static} - handleClientSelectCharacter()
      }
    }
  }
  

  namespace dev.spiritworker {
    namespace server.game {
      class dev.spiritworker.server.game.GameServer {
          - authServer : ServerData
          - channels : List<WorldServer>
          - characters : Map<String, GameCharacter>
          - id : int
          - name : String
          + GameServer()
          + addCharacter()
          + getAuthServer()
          + getChannelByIndex()
          + getChannelCount()
          + getChannels()
          + getCharacters()
          + getCurrentPlayers()
          + getServerId()
          + getServerName()
          + onStart()
          + registerWorldServer()
          + removeCharacter()
      }
    }
  }
  

  namespace dev.spiritworker {
    namespace server.game {
      class dev.spiritworker.server.game.GameServerInitializer {
          - server : GameServer
          + GameServerInitializer()
          + initChannel()
      }
    }
  }
  

  namespace dev.spiritworker {
    namespace server.game {
      class dev.spiritworker.server.game.GameSession {
          - characters : List<GameCharacter>
          - server : GameServer
          + GameSession()
          + getCharacters()
          + getServer()
          + onConnect()
          + onDisconnect()
          + setCharacterList()
          # handleMessage()
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
