@startuml

title __DATABASE's Class Diagram__\n

  namespace dev.spiritworker {
    namespace database {
      class dev.spiritworker.database.DatabaseCounter {
          - count : int
          - id : String
          + DatabaseCounter()
          + DatabaseCounter()
          + getNextId()
      }
    }
  }
  

  namespace dev.spiritworker {
    namespace database {
      class dev.spiritworker.database.DatabaseHelper {
          {static} + createAccessKey()
          {static} + createAccount()
          {static} + createCharacter()
          {static} + deleteAccessKey()
          {static} + deleteAccount()
          {static} + deleteCharacter()
          {static} + deleteInventoryAndEquippedItems()
          {static} + deleteItem()
          {static} + getAccessKey()
          {static} + getAccountById()
          {static} + getAccountByToken()
          {static} + getBankItems()
          {static} + getBankUpgradeData()
          {static} + getCharacterById()
          {static} + getCharacterCount()
          {static} + getCharacterList()
          {static} + getCharacterSkills()
          {static} + getCosmeticItems()
          {static} + getInventoryItems()
          {static} + getWeaponItem()
          {static} + isCharacterNameTaken()
          {static} + saveBankUpgradeData()
          {static} + saveCharacter()
          {static} + saveCharacterSkills()
          {static} + saveItem()
      }
    }
  }
  

  namespace dev.spiritworker {
    namespace database {
      class dev.spiritworker.database.DatabaseManager {
          {static} - datastore : Datastore
          {static} - mappedClasses : Class<?>[]
          {static} - mongoClient : MongoClient
          {static} - morphia : Morphia
          {static} + getConnection()
          {static} + getDatastore()
          {static} + getMongoClient()
          {static} + getNextId()
          {static} + initialize()
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
